FROM mcr.microsoft.com/dotnet/sdk:3.1.404-alpine3.12
RUN apk --no-cache add openjdk11-jre-headless && dotnet tool install --global dotnet-sonarscanner --version 5.0.4 && dotnet tool install --global coverlet.console --version 1.7.2
ENV PATH="$PATH:/root/.dotnet/tools"
